"""init

Revision ID: e0e8f781ec72
Revises: 
Create Date: 2026-04-24 13:17:31.080414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0e8f781ec72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'needs_review', 'failed', 'done', name='jobstatus'), nullable=False),
    sa.Column('stage', sa.Enum('parse', 'translate', 'reassemble', 'done', 'failed', name='jobstage'), nullable=True),
    sa.Column('source_lang', sa.String(length=64), nullable=False),
    sa.Column('target_lang', sa.String(length=64), nullable=False),
    sa.Column('detected_lang', sa.String(length=64), nullable=True),
    sa.Column('input_format', sa.String(length=16), nullable=False),
    sa.Column('input_path', sa.Text(), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('segments_done', sa.Integer(), nullable=False),
    sa.Column('segments_total', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('has_tracked_changes', sa.Boolean(), nullable=False),
    sa.Column('tracked_changes_action', sa.Enum('strip', 'preserve', name='trackedchangesaction'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('seq_in_job', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('structural_position', sa.Text(), nullable=False),
    sa.Column('is_comment', sa.Boolean(), nullable=False),
    sa.Column('is_inserted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_job_id'), 'segments', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_job_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_table('jobs')
    # ### end Alembic commands ###
